version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "12:00"
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad

  - package-ecosystem: npm
    directories:
      - '/infra/aws'
      - '/infra/azuread'
      - '/app/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "12:00"
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      npm:
        patterns:
          - "*"
