packages:
  - ./infra/aws
  - ./infra/azuread
  - ./app

allowBuilds:
  '@swc/core': false
  sharp: false
  unrs-resolver: false

minimumReleaseAge: 10080 # 7 days in minutes
minimumReleaseAgeExclude:
  - '@next/*'
  - fast-xml-builder@1.1.7
  - next@16.2.6
  - js-cookie@3.0.6

overrides:
  eslint-import-resolver-typescript: '>=4'
  fast-xml-builder@<=1.1.6: ^1.1.7
  fast-xml-parser@<5.7.0: '>=5.7.0'
  js-cookie@<=3.0.5: ^3.0.6
  next@>=16.0.0 <16.2.6: ^16.2.6
  postcss@<8.5.10: '>=8.5.10'
  semver: '>=7'
  uuid@<14.0.0: '>=14.0.0'

trustPolicy: no-downgrade
