name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false

    - name: Install pnpm
      uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1.0.0

    - name: generate dotenv
      env:
        DOTENV: ${{ secrets.DOTENV }}
      run:
        echo "$DOTENV" > app/.env

    - name: build
      run: pnpm -r build
