name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Install pnpm
      uses: pnpm/setup@4700d737c3d7a2e7199f3d42a920f0bf7f34e411 # v2.0.1

    - name: generate dotenv
      env:
        DOTENV: ${{ secrets.DOTENV }}
      run:
        echo "$DOTENV" > app/.env

    - name: build
      run: pnpm -r build
